# Generated by Django 4.2.6 on 2023-11-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('twitter_icon', models.CharField(max_length=50)),
                ('insta_icon', models.CharField(max_length=50)),
                ('facebook_icon', models.CharField(max_length=50)),
                ('linkedin_icon', models.CharField(max_length=50)),
            ],
        ),
    ]
