# Generated by Django 4.2.6 on 2023-11-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_remove_team_heading_remove_team_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='images/'),
        ),
    ]
